spring.application.name=auth-service

server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/oauth_db

spring.data.mongodb.database=oauth_db

spring.data.mongodb.auto-index-creation=true

management.endpoints.web.exposure.include=*

logging.level.org.springframework.security=DEBUG

jwt.secret=ThisIsMyVeryStrongSecretKeyForEduPathAuthService2026Minimum32Characters
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000
jwt.issuer=EduPath-Auth-Service
