spring.application.name=career-service

server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/edupath_career_db
spring.datasource.username=root
spring.datasource.password=nath@1827

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect